---
- name: Example Playbook
  hosts: all
  tasks:
    - name: Include ansible-docker
      include_role:
        name: ansible-docker
    - name: Include ansible-awx
      include_role:
        name: ansible-awx
