---
- name: Converge (Install Pre-Reqs)
  hosts: all
  tasks:
    - name: Include ansible-bootstrap-python
      include_role:
        name: ansible-bootstrap-python
    - name: Include ansible-docker
      include_role:
        name: ansible-docker

- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-awx
      include_role:
        name: ansible-awx
